name: Module Regression Test - Complete

on:
  pull_request:
    paths:
      - examples/regression/current/*.tf
      - examples/regression/next/*.tf
    types:
      - opened
      - synchronize
      - reopened
      - closed
    branches-ignore:
      - renovate/*

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  current_version_deploy:
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    uses: DND-IT/github-workflows/.github/workflows/tf-feature.yaml@v2
    with:
      environment: examples
      tf_dir: examples/regression/current

  next_version_deploy:
    needs: current_version_deploy
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    uses: DND-IT/github-workflows/.github/workflows/tf-feature.yaml@v2
    with:
      environment: examples
      tf_dir: examples/regression/next

  current_version_destroy:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    uses: DND-IT/github-workflows/.github/workflows/tf-cleanup.yaml@v2
    with:
      environment: examples
      tf_dir: examples/regression/current

  next_version_destroy:
    needs: current_version_destroy
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    uses: DND-IT/github-workflows/.github/workflows/tf-cleanup.yaml@v2
    with:
      environment: examples
      tf_dir: examples/regression/next
