name: Release on tag

# Tag should have the same version as in the `setup.py`
on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    uses: tx-pts-dai/github-workflows/.github/workflows/gh-release.yaml@v2.0.0
    with:
      tag: ${{ github.ref_name }}
