name: Module Test - Complete

on:
  pull_request:
    paths:
      - examples/complete/current/*.tf
      - examples/complete/next/*.tf
    types:
      - opened
      - synchronize
      - reopened
      - closed
    branches-ignore:
      - renovate/*

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  current_version_deploy:
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    uses: DND-IT/github-workflows/.github/workflows/tf-feature.yaml@v3
    with:
      environment: examples
      tf_dir: examples/complete/current

  next_version_deploy:
    needs: current_version_deploy
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    uses: DND-IT/github-workflows/.github/workflows/tf-feature.yaml@v3
    with:
      environment: examples
      tf_dir: examples/complete/next

  feature_destroy:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    uses: DND-IT/github-workflows/.github/workflows/tf-cleanup.yaml@v3
    with:
      environment: examples
      tf_dir: examples/complete/next
